export const customizationGroups = [
  {
    id: "1",
    name: "Head",
    position: 1,
    startingAsset: "Head_01",
    colorPaletteName: "Skin",
    removable: false,
  },
  {
    id: "2",
    name: "Hair",
    position: 2,
    startingAsset: "Hair_01",
    colorPaletteName: "Hair",
    removable: true,
  },
  {
    id: "3",
    name: "Eyes",
    position: 3,
    startingAsset: "Eyes_01",
    colorPaletteName: null,
    removable: false,
  },
  {
    id: "4",
    name: "Eyebrows",
    position: 4,
    startingAsset: "Eyebrow_01",
    colorPaletteName: "Hair",
    removable: false,
  },
  {
    id: "5",
    name: "Nose",
    position: 5,
    startingAsset: "Nose_01",
    colorPaletteName: "Skin",
    removable: false,
  },
  {
    id: "6",
    name: "Facial Hair",
    position: 6,
    startingAsset: null,
    colorPaletteName: "Hair",
    removable: true,
  },
  {
    id: "7",
    name: "Glasses",
    position: 7,
    startingAsset: null,
    colorPaletteName: null,
    removable: true,
  },
  {
    id: "8",
    name: "Hat",
    position: 8,
    startingAsset: null,
    colorPaletteName: null,
    removable: true,
  },
  {
    id: "9",
    name: "Top",
    position: 9,
    startingAsset: "Top_01",
    colorPaletteName: "Clothes",
    removable: false,
  },
  {
    id: "10",
    name: "Bottom",
    position: 10,
    startingAsset: "Bottom_01",
    colorPaletteName: "Clothes",
    removable: false,
  },
  {
    id: "11",
    name: "Shoes",
    position: 11,
    startingAsset: "Shoes_01",
    colorPaletteName: "Clothes",
    removable: true,
  },
  {
    id: "12",
    name: "Accessories",
    position: 12,
    startingAsset: null,
    colorPaletteName: null,
    removable: true,
  },
];
