export const customizationAssets = [
  {
    groupId: "1",
    name: "Head_01",
    thumbnail: "/images/avatar/customization/head.jpg",
    url: "/models/avatar/customization/Head.001.glb",
  },
  {
    groupId: "1",
    name: "Head_02",
    thumbnail: "/images/avatar/customization/head.jpg",
    url: "/models/avatar/customization/Head.002.glb",
  },
  {
    groupId: "1",
    name: "Head_03",
    thumbnail: "/images/avatar/customization/head.jpg",
    url: "/models/avatar/customization/Head.003.glb",
  },
  {
    groupId: "1",
    name: "Head_04",
    thumbnail: "/images/avatar/customization/head.jpg",
    url: "/models/avatar/customization/Head.004.glb",
  },
  {
    groupId: "2",
    name: "Hair_01",
    thumbnail: "/images/avatar/customization/hair.jpg",
    url: "/models/avatar/customization/Hair.001.glb",
  },
  {
    groupId: "2",
    name: "Hair_02",
    thumbnail: "/images/avatar/customization/hair.jpg",
    url: "/models/avatar/customization/Hair.002.glb",
  },
  {
    groupId: "2",
    name: "Hair_03",
    thumbnail: "/images/avatar/customization/hair.jpg",
    url: "/models/avatar/customization/Hair.003.glb",
  },
  {
    groupId: "2",
    name: "Hair_04",
    thumbnail: "/images/avatar/customization/hair.jpg",
    url: "/models/avatar/customization/Hair.004.glb",
  },
  {
    groupId: "2",
    name: "Hair_05",
    thumbnail: "/images/avatar/customization/hair.jpg",
    url: "/models/avatar/customization/Hair.005.glb",
  },
  {
    groupId: "2",
    name: "Hair_06",
    thumbnail: "/images/avatar/customization/hair.jpg",
    url: "/models/avatar/customization/Hair.006.glb",
  },
  {
    groupId: "2",
    name: "Hair_07",
    thumbnail: "/images/avatar/customization/hair.jpg",
    url: "/models/avatar/customization/Hair.007.glb",
  },
  {
    groupId: "2",
    name: "Hair_08",
    thumbnail: "/images/avatar/customization/hair.jpg",
    url: "/models/avatar/customization/Hair.008.glb",
  },
  {
    groupId: "2",
    name: "Hair_09",
    thumbnail: "/images/avatar/customization/hair.jpg",
    url: "/models/avatar/customization/Hair.009.glb",
  },
  {
    groupId: "2",
    name: "Hair_10",
    thumbnail: "/images/avatar/customization/hair.jpg",
    url: "/models/avatar/customization/Hair.010.glb",
  },
  {
    groupId: "2",
    name: "Hair_11",
    thumbnail: "/images/avatar/customization/hair.jpg",
    url: "/models/avatar/customization/Hair.011.glb",
  },
  {
    groupId: "3",
    name: "Eyes_01",
    thumbnail: "/images/avatar/customization/eyes.jpg",
    url: "/models/avatar/customization/Eyes.001.glb",
  },
  {
    groupId: "3",
    name: "Eyes_02",
    thumbnail: "/images/avatar/customization/eyes.jpg",
    url: "/models/avatar/customization/Eyes.002.glb",
  },
  {
    groupId: "3",
    name: "Eyes_03",
    thumbnail: "/images/avatar/customization/eyes.jpg",
    url: "/models/avatar/customization/Eyes.003.glb",
  },
  {
    groupId: "4",
    name: "Eyebrow_01",
    thumbnail: "/images/avatar/customization/eyebrows.jpg",
    url: "/models/avatar/customization/Eyebrow.001.glb",
  },
  {
    groupId: "4",
    name: "Eyebrow_02",
    thumbnail: "/images/avatar/customization/eyebrows.jpg",
    url: "/models/avatar/customization/Eyebrow.002.glb",
  },
  {
    groupId: "4",
    name: "Eyebrow_03",
    thumbnail: "/images/avatar/customization/eyebrows.jpg",
    url: "/models/avatar/customization/Eyebrow.003.glb",
  },
  {
    groupId: "4",
    name: "Eyebrow_04",
    thumbnail: "/images/avatar/customization/eyebrows.jpg",
    url: "/models/avatar/customization/Eyebrow.004.glb",
  },
  {
    groupId: "5",
    name: "Nose_01",
    thumbnail: "/images/avatar/customization/nose.jpg",
    url: "/models/avatar/customization/Nose.001.glb",
  },
  {
    groupId: "5",
    name: "Nose_02",
    thumbnail: "/images/avatar/customization/nose.jpg",
    url: "/models/avatar/customization/Nose.002.glb",
  },
  {
    groupId: "5",
    name: "Nose_03",
    thumbnail: "/images/avatar/customization/nose.jpg",
    url: "/models/avatar/customization/Nose.003.glb",
  },
  {
    groupId: "6",
    name: "FacialHair_01",
    thumbnail: "/images/avatar/customization/facialhair.jpg",
    url: "/models/avatar/customization/FacialHair.001.glb",
  },
  {
    groupId: "6",
    name: "FacialHair_02",
    thumbnail: "/images/avatar/customization/facialhair.jpg",
    url: "/models/avatar/customization/FacialHair.002.glb",
  },
  {
    groupId: "6",
    name: "FacialHair_03",
    thumbnail: "/images/avatar/customization/facialhair.jpg",
    url: "/models/avatar/customization/FacialHair.003.glb",
  },
  {
    groupId: "6",
    name: "FacialHair_04",
    thumbnail: "/images/avatar/customization/facialhair.jpg",
    url: "/models/avatar/customization/FacialHair.004.glb",
  },
  {
    groupId: "6",
    name: "FacialHair_05",
    thumbnail: "/images/avatar/customization/facialhair.jpg",
    url: "/models/avatar/customization/FacialHair.005.glb",
  },
  {
    groupId: "6",
    name: "FacialHair_06",
    thumbnail: "/images/avatar/customization/facialhair.jpg",
    url: "/models/avatar/customization/FacialHair.006.glb",
  },
  {
    groupId: "6",
    name: "FacialHair_07",
    thumbnail: "/images/avatar/customization/facialhair.jpg",
    url: "/models/avatar/customization/FacialHair.007.glb",
  },
  {
    groupId: "7",
    name: "Glasses_01",
    thumbnail: "/images/avatar/customization/glasses.jpg",
    url: "/models/avatar/customization/Glasses.001.glb",
  },
  {
    groupId: "7",
    name: "Glasses_02",
    thumbnail: "/images/avatar/customization/glasses.jpg",
    url: "/models/avatar/customization/Glasses.002.glb",
  },
  {
    groupId: "7",
    name: "Glasses_03",
    thumbnail: "/images/avatar/customization/glasses.jpg",
    url: "/models/avatar/customization/Glasses.003.glb",
  },
  {
    groupId: "7",
    name: "Glasses_04",
    thumbnail: "/images/avatar/customization/glasses.jpg",
    url: "/models/avatar/customization/Glasses.004.glb",
  },
  {
    groupId: "8",
    name: "Hat_01",
    thumbnail: "/images/avatar/customization/hat.jpg",
    url: "/models/avatar/customization/Hat.001.glb",
  },
  {
    groupId: "8",
    name: "Hat_02",
    thumbnail: "/images/avatar/customization/hat.jpg",
    url: "/models/avatar/customization/Hat.002.glb",
  },
  {
    groupId: "8",
    name: "Hat_03",
    thumbnail: "/images/avatar/customization/hat.jpg",
    url: "/models/avatar/customization/Hat.003.glb",
  },
  {
    groupId: "8",
    name: "Hat_04",
    thumbnail: "/images/avatar/customization/hat.jpg",
    url: "/models/avatar/customization/Hat.004.glb",
  },
  {
    groupId: "9",
    name: "Top_01",
    thumbnail: "/images/avatar/customization/top.jpg",
    url: "/models/avatar/customization/Top.001.glb",
  },
  {
    groupId: "9",
    name: "Top_02",
    thumbnail: "/images/avatar/customization/top.jpg",
    url: "/models/avatar/customization/Top.002.glb",
  },
  {
    groupId: "9",
    name: "Top_03",
    thumbnail: "/images/avatar/customization/top.jpg",
    url: "/models/avatar/customization/Top.003.glb",
  },
  {
    groupId: "10",
    name: "Bottom_01",
    thumbnail: "/images/avatar/customization/bottom.jpg",
    url: "/models/avatar/customization/Bottom.001.glb",
  },
  {
    groupId: "10",
    name: "Bottom_02",
    thumbnail: "/images/avatar/customization/bottom.jpg",
    url: "/models/avatar/customization/Bottom.002.glb",
  },
  {
    groupId: "10",
    name: "Bottom_03",
    thumbnail: "/images/avatar/customization/bottom.jpg",
    url: "/models/avatar/customization/Bottom.003.glb",
  },
  {
    groupId: "11",
    name: "Shoes_01",
    thumbnail: "/images/avatar/customization/shoes.jpg",
    url: "/models/avatar/customization/Shoes.001.glb",
  },
  {
    groupId: "11",
    name: "Shoes_02",
    thumbnail: "/images/avatar/customization/shoes.jpg",
    url: "/models/avatar/customization/Shoes.002.glb",
  },
];
