/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function World(props) {
  const { nodes, materials } = useGLTF('./models/environment/world.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials['wood.001']}
        position={[-18.85, 1.145, -9.711]}
        rotation={[Math.PI, -1.541, Math.PI]}
        scale={[5.374, 5.179, 5.374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials['wood.001']}
        position={[18.577, 1.145, 8.315]}
        rotation={[0, 1.541, 0]}
        scale={[5.374, 5.179, 5.374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials['wood.001']}
        position={[-3.788, 1.047, -39.81]}
        rotation={[-Math.PI, 0.03, -Math.PI]}
        scale={[5.374, 5.179, 5.374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials['wood.001']}
        position={[4.09, 1.047, 37.607]}
        rotation={[0, -0.03, 0]}
        scale={[5.374, 5.179, 5.374]}
      />
      <group position={[-24.175, 0, -25.927]} scale={1.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials['Banana Trunk']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_1.geometry}
          material={materials['Banana Leaf 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_2.geometry}
          material={materials['Banana Leaf 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_3.geometry}
          material={materials['Banana Leaf 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_4.geometry}
          material={materials['Banana Leaf 1']}
        />
      </group>
      <group position={[-23.727, 0, -16.069]} rotation={[-Math.PI, 1.058, -Math.PI]} scale={1.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003.geometry}
          material={materials['Banana Trunk']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_1.geometry}
          material={materials['Banana Leaf 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_2.geometry}
          material={materials['Banana Leaf 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_3.geometry}
          material={materials['Banana Leaf 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_4.geometry}
          material={materials['Banana Leaf 1']}
        />
      </group>
      <group position={[-31.339, 0, -21.384]} rotation={[Math.PI, -0.606, Math.PI]} scale={1.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004.geometry}
          material={materials['Banana Trunk']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_1.geometry}
          material={materials['Banana Leaf 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_2.geometry}
          material={materials['Banana Leaf 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_3.geometry}
          material={materials['Banana Leaf 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_4.geometry}
          material={materials['Banana Leaf 1']}
        />
      </group>
      <group position={[-22.58, 0, -6.546]} rotation={[-Math.PI, 0.64, -Math.PI]} scale={1.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005.geometry}
          material={materials['Banana Trunk']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_1.geometry}
          material={materials['Banana Leaf 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_2.geometry}
          material={materials['Banana Leaf 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_3.geometry}
          material={materials['Banana Leaf 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_4.geometry}
          material={materials['Banana Leaf 1']}
        />
      </group>
      <group position={[-18.386, 0, -48.717]} scale={1.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006.geometry}
          material={materials['Banana Trunk']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_1.geometry}
          material={materials['Banana Leaf 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_2.geometry}
          material={materials['Banana Leaf 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_3.geometry}
          material={materials['Banana Leaf 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_4.geometry}
          material={materials['Banana Leaf 1']}
        />
      </group>
      <group position={[-22.816, 0, 28.026]} rotation={[-Math.PI, 1.28, -Math.PI]} scale={1.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle007.geometry}
          material={materials['Banana Trunk']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle007_1.geometry}
          material={materials['Banana Leaf 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle007_2.geometry}
          material={materials['Banana Leaf 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle007_3.geometry}
          material={materials['Banana Leaf 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle007_4.geometry}
          material={materials['Banana Leaf 1']}
        />
      </group>
      <group position={[23.446, 0, -17.627]} scale={1.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle014.geometry}
          material={materials['Banana Trunk']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle014_1.geometry}
          material={materials['Banana Leaf 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle014_2.geometry}
          material={materials['Banana Leaf 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle014_3.geometry}
          material={materials['Banana Leaf 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle014_4.geometry}
          material={materials['Banana Leaf 1']}
        />
      </group>
      <group position={[27.755, 0, -10.576]} rotation={[0, 1.322, 0]} scale={1.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle015.geometry}
          material={materials['Banana Trunk']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle015_1.geometry}
          material={materials['Banana Leaf 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle015_2.geometry}
          material={materials['Banana Leaf 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle015_3.geometry}
          material={materials['Banana Leaf 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle015_4.geometry}
          material={materials['Banana Leaf 1']}
        />
      </group>
      <group position={[23.695, 0, 0.572]} rotation={[-Math.PI, 1.241, -Math.PI]} scale={1.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle016.geometry}
          material={materials['Banana Trunk']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle016_1.geometry}
          material={materials['Banana Leaf 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle016_2.geometry}
          material={materials['Banana Leaf 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle016_3.geometry}
          material={materials['Banana Leaf 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle016_4.geometry}
          material={materials['Banana Leaf 1']}
        />
      </group>
      <group position={[24.916, 0, 23.326]} rotation={[-Math.PI, 1.241, -Math.PI]} scale={1.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle017.geometry}
          material={materials['Banana Trunk']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle017_1.geometry}
          material={materials['Banana Leaf 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle017_2.geometry}
          material={materials['Banana Leaf 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle017_3.geometry}
          material={materials['Banana Leaf 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle017_4.geometry}
          material={materials['Banana Leaf 1']}
        />
      </group>
      <group position={[31.994, 0, 31.872]} rotation={[0, -0.119, 0]} scale={1.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle018.geometry}
          material={materials['Banana Trunk']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle018_1.geometry}
          material={materials['Banana Leaf 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle018_2.geometry}
          material={materials['Banana Leaf 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle018_3.geometry}
          material={materials['Banana Leaf 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle018_4.geometry}
          material={materials['Banana Leaf 1']}
        />
      </group>
      <group position={[22.67, 0, 37.819]} rotation={[-Math.PI, 0.202, -Math.PI]} scale={1.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle019.geometry}
          material={materials['Banana Trunk']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle019_1.geometry}
          material={materials['Banana Leaf 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle019_2.geometry}
          material={materials['Banana Leaf 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle019_3.geometry}
          material={materials['Banana Leaf 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle019_4.geometry}
          material={materials['Banana Leaf 1']}
        />
      </group>
      <group position={[-20.793, 0, -34.229]} rotation={[0, 0.884, 0]} scale={1.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002.geometry}
          material={materials['Banana Trunk']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002_1.geometry}
          material={materials['Banana Leaf 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002_2.geometry}
          material={materials['Banana Leaf 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002_3.geometry}
          material={materials['Banana Leaf 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002_4.geometry}
          material={materials['Banana Leaf 1']}
        />
      </group>
      <group position={[29.96, 2.117, -49.022]} rotation={[Math.PI / 2, 0, -1.951]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube038.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube038_1.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[35.126, 2.117, 2.15]} rotation={[Math.PI / 2, 0, -1.951]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_2.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[36.746, 2.004, 40.328]} rotation={[Math.PI / 2, 0, -0.435]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_2.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[4.912, 2.117, -62.053]} rotation={[Math.PI / 2, 0, -1.951]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_2.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[-17.461, 0.682, -60.653]} rotation={[Math.PI / 2, 0, -1.951]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_2.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[-24.821, 1.973, -40.738]} rotation={[Math.PI / 2, 0, -2.404]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_1.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[-35.773, 1.973, -21.105]} rotation={[Math.PI / 2, 0, -2.404]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_1.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[-23.43, 1.973, 5.358]} rotation={[Math.PI / 2, 0, -2.404]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_1.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[-29.479, 1.973, -2.157]} rotation={[Math.PI / 2, 0, -2.404]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube029.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube029_1.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[-32.208, 1.973, 22.265]} rotation={[Math.PI / 2, 0, -2.404]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_1.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[44.212, 0.682, -13.938]} rotation={[Math.PI / 2, 0, -1.951]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[-46.161, 2.117, -9.814]} rotation={[Math.PI / 2, 0, -1.951]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_2.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[-44.067, 0.682, 8.833]} rotation={[Math.PI / 2, 0, -1.951]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_2.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[-40.275, 2.117, -39.892]} rotation={[Math.PI / 2, 0, -1.951]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_2.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[43.718, 2.117, 25.701]} rotation={[Math.PI / 2, 0, 1.401]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials['Material.005']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials['rock.001']}
        position={[-34.219, 1.085, -43.255]}
        rotation={[0, -0.228, 0]}
        scale={[0.501, 1.113, 0.405]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials['rock.002']}
        position={[-33.67, -0.151, -31.841]}
        scale={0.205}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials.rock}
        position={[-34.567, 3.998, -11.901]}
        rotation={[-Math.PI, 1.049, -Math.PI]}
        scale={[0.373, 0.276, 0.318]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['rock.001']}
        position={[-34.242, 0.753, 9.23]}
        rotation={[Math.PI, -0.787, Math.PI]}
        scale={[0.501, 1.113, 0.405]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.rock}
        position={[-26.6, 0.289, 9.492]}
        rotation={[Math.PI, -0.491, Math.PI]}
        scale={[0.373, 0.276, 0.318]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.rock}
        position={[-29.704, 2.997, 33.959]}
        rotation={[Math.PI, -1.557, Math.PI]}
        scale={[0.373, 0.431, 0.318]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials['rock.002']}
        position={[-8.36, 2.142, -50.718]}
        scale={0.205}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['rock.001']}
        position={[-34.219, 1.085, -43.255]}
        rotation={[0, -0.228, 0]}
        scale={[0.501, 1.113, 0.405]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials.rock}
        position={[21.017, 0.289, -59.891]}
        rotation={[Math.PI, -0.07, Math.PI]}
        scale={[0.373, 0.276, 0.318]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials['rock.001']}
        position={[37.288, 9.682, -28.294]}
        rotation={[0, -0.247, 0]}
        scale={[0.501, 1.113, 0.405]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials.rock}
        position={[34.76, 2.997, -7.617]}
        rotation={[Math.PI, -0.068, Math.PI]}
        scale={[0.373, 0.431, 0.318]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials.rock}
        position={[33.232, 2.997, 14.663]}
        rotation={[Math.PI, -0.068, Math.PI]}
        scale={[0.373, 0.431, 0.318]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials['rock.002']}
        position={[19.612, -0.151, 3.8]}
        scale={0.205}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.007']}
      />
    </group>
  )
}

useGLTF.preload('./models/environment/world.glb')
