export const customizationAssets = [
  {
    groupId: "1",
    name: "Head_01",
    thumbnail: "/images/avatar/customization/Head_01.png",
    url: "/models/avatar/customization/Head.001.glb",
    lockedGroups: null,
  },
  {
    groupId: "1",
    name: "Head_02",
    thumbnail: "/images/avatar/customization/Head_02.png",
    url: "/models/avatar/customization/Head.002.glb",
    lockedGroups: null,
  },
  {
    groupId: "1",
    name: "Head_03",
    thumbnail: "/images/avatar/customization/Head_03.png",
    url: "/models/avatar/customization/Head.003.glb",
    lockedGroups: null,
  },
  {
    groupId: "1",
    name: "Head_04",
    thumbnail: "/images/avatar/customization/Head_04.png",
    url: "/models/avatar/customization/Head.004.glb",
    lockedGroups: null,
  },
  {
    groupId: "2",
    name: "Hair_01",
    thumbnail: "/images/avatar/customization/Hair_01.png",
    url: "/models/avatar/customization/Hair.001.glb",
    lockedGroups: null,
  },
  {
    groupId: "2",
    name: "Hair_02",
    thumbnail: "/images/avatar/customization/Hair_02.png",
    url: "/models/avatar/customization/Hair.002.glb",
    lockedGroups: null,
  },
  {
    groupId: "2",
    name: "Hair_03",
    thumbnail: "/images/avatar/customization/Hair_03.png",
    url: "/models/avatar/customization/Hair.003.glb",
    lockedGroups: null,
  },
  {
    groupId: "2",
    name: "Hair_04",
    thumbnail: "/images/avatar/customization/Hair_04.png",
    url: "/models/avatar/customization/Hair.004.glb",
    lockedGroups: null,
  },
  {
    groupId: "2",
    name: "Hair_05",
    thumbnail: "/images/avatar/customization/Hair_05.png",
    url: "/models/avatar/customization/Hair.005.glb",
    lockedGroups: null,
  },
  {
    groupId: "2",
    name: "Hair_06",
    thumbnail: "/images/avatar/customization/Hair_06.png",
    url: "/models/avatar/customization/Hair.006.glb",
    lockedGroups: null,
  },
  {
    groupId: "2",
    name: "Hair_07",
    thumbnail: "/images/avatar/customization/Hair_07.png",
    url: "/models/avatar/customization/Hair.007.glb",
    lockedGroups: null,
  },
  {
    groupId: "2",
    name: "Hair_08",
    thumbnail: "/images/avatar/customization/Hair_08.png",
    url: "/models/avatar/customization/Hair.008.glb",
    lockedGroups: null,
  },
  {
    groupId: "2",
    name: "Hair_09",
    thumbnail: "/images/avatar/customization/Hair_09.png",
    url: "/models/avatar/customization/Hair.009.glb",
    lockedGroups: null,
  },
  {
    groupId: "2",
    name: "Hair_10",
    thumbnail: "/images/avatar/customization/Hair_10.png",
    url: "/models/avatar/customization/Hair.010.glb",
    lockedGroups: null,
  },
  {
    groupId: "2",
    name: "Hair_11",
    thumbnail: "/images/avatar/customization/Hair_11.png",
    url: "/models/avatar/customization/Hair.011.glb",
    lockedGroups: null,
  },
  {
    groupId: "3",
    name: "Eyes_01",
    thumbnail: "/images/avatar/customization/Eyes_01.png",
    url: "/models/avatar/customization/Eyes.001.glb",
    lockedGroups: null,
  },
  {
    groupId: "3",
    name: "Eyes_02",
    thumbnail: "/images/avatar/customization/Eyes_02.png",
    url: "/models/avatar/customization/Eyes.002.glb",
    lockedGroups: null,
  },
  {
    groupId: "3",
    name: "Eyes_03",
    thumbnail: "/images/avatar/customization/Eyes_03.png",
    url: "/models/avatar/customization/Eyes.003.glb",
    lockedGroups: null,
  },
  {
    groupId: "4",
    name: "Eyebrow_01",
    thumbnail: "/images/avatar/customization/Eyebrow_01.png",
    url: "/models/avatar/customization/Eyebrow.001.glb",
    lockedGroups: null,
  },
  {
    groupId: "4",
    name: "Eyebrow_02",
    thumbnail: "/images/avatar/customization/Eyebrow_02.png",
    url: "/models/avatar/customization/Eyebrow.002.glb",
    lockedGroups: null,
  },
  {
    groupId: "4",
    name: "Eyebrow_03",
    thumbnail: "/images/avatar/customization/Eyebrow_03.png",
    url: "/models/avatar/customization/Eyebrow.003.glb",
    lockedGroups: null,
  },
  {
    groupId: "5",
    name: "Nose_01",
    thumbnail: "/images/avatar/customization/Nose_01.png",
    url: "/models/avatar/customization/Nose.001.glb",
    lockedGroups: null,
  },
  {
    groupId: "5",
    name: "Nose_02",
    thumbnail: "/images/avatar/customization/Nose_02.png",
    url: "/models/avatar/customization/Nose.002.glb",
    lockedGroups: null,
  },
  {
    groupId: "5",
    name: "Nose_03",
    thumbnail: "/images/avatar/customization/Nose_03.png",
    url: "/models/avatar/customization/Nose.003.glb",
    lockedGroups: null,
  },
  {
    groupId: "6",
    name: "FacialHair_01",
    thumbnail: "/images/avatar/customization/FacialHair_01.png",
    url: "/models/avatar/customization/FacialHair.001.glb",
    lockedGroups: null,
  },
  {
    groupId: "6",
    name: "FacialHair_02",
    thumbnail: "/images/avatar/customization/FacialHair_02.png",
    url: "/models/avatar/customization/FacialHair.002.glb",
    lockedGroups: null,
  },
  {
    groupId: "6",
    name: "FacialHair_03",
    thumbnail: "/images/avatar/customization/FacialHair_03.png",
    url: "/models/avatar/customization/FacialHair.003.glb",
    lockedGroups: null,
  },
  {
    groupId: "6",
    name: "FacialHair_04",
    thumbnail: "/images/avatar/customization/FacialHair_04.png",
    url: "/models/avatar/customization/FacialHair.004.glb",
    lockedGroups: null,
  },
  {
    groupId: "7",
    name: "Glasses_01",
    thumbnail: "/images/avatar/customization/Glasses_01.png",
    url: "/models/avatar/customization/Glasses.001.glb",
    lockedGroups: null,
  },
  {
    groupId: "7",
    name: "Glasses_02",
    thumbnail: "/images/avatar/customization/Glasses_02.png",
    url: "/models/avatar/customization/Glasses.002.glb",
    lockedGroups: null,
  },
  {
    groupId: "7",
    name: "Glasses_03",
    thumbnail: "/images/avatar/customization/Glasses_03.png",
    url: "/models/avatar/customization/Glasses.003.glb",
    lockedGroups: null,
  },
  {
    groupId: "8",
    name: "Hat_01",
    thumbnail: "/images/avatar/customization/Hat_01.png",
    url: "/models/avatar/customization/Hat.001.glb",
    lockedGroups: null,
  },
  {
    groupId: "8",
    name: "Hat_02",
    thumbnail: "/images/avatar/customization/Hat_02.png",
    url: "/models/avatar/customization/Hat.002.glb",
    lockedGroups: null,
  },
  {
    groupId: "9",
    name: "Top_01",
    thumbnail: "/images/avatar/customization/Top_01.png",
    url: "/models/avatar/customization/Top.001.glb",
    lockedGroups: null,
  },
  {
    groupId: "9",
    name: "Top_02",
    thumbnail: "/images/avatar/customization/Top_02.png",
    url: "/models/avatar/customization/Top.002.glb",
    lockedGroups: null,
  },
  {
    groupId: "9",
    name: "Top_03",
    thumbnail: "/images/avatar/customization/Top_03.png",
    url: "/models/avatar/customization/Top.003.glb",
    lockedGroups: ["10"],
  },
  {
    groupId: "10",
    name: "Bottom_01",
    thumbnail: "/images/avatar/customization/Bottom_01.png",
    url: "/models/avatar/customization/Bottom.001.glb",
    lockedGroups: null,
  },
  {
    groupId: "10",
    name: "Bottom_02",
    thumbnail: "/images/avatar/customization/Bottom_02.png",
    url: "/models/avatar/customization/Bottom.002.glb",
    lockedGroups: null,
  },
  {
    groupId: "10",
    name: "Bottom_03",
    thumbnail: "/images/avatar/customization/Bottom_03.png",
    url: "/models/avatar/customization/Bottom.003.glb",
    lockedGroups: null,
  },
  {
    groupId: "11",
    name: "Shoes_01",
    thumbnail: "/images/avatar/customization/Shoes_01.png",
    url: "/models/avatar/customization/Shoes.001.glb",
    lockedGroups: null,
  },
  {
    groupId: "11",
    name: "Shoes_02",
    thumbnail: "/images/avatar/customization/Shoes_02.png",
    url: "/models/avatar/customization/Shoes.002.glb",
    lockedGroups: null,
  },
  {
    groupId: "12",
    name: "Earring_01",
    thumbnail: "/images/avatar/customization/Earring_01.png",
    url: "/models/avatar/customization/Earring.001.glb",
    lockedGroups: null,
  },
  {
    groupId: "12",
    name: "Earring_02",
    thumbnail: "/images/avatar/customization/Earring_02.png",
    url: "/models/avatar/customization/Earring.002.glb",
    lockedGroups: null,
  },
  {
    groupId: "12",
    name: "Earring_03",
    thumbnail: "/images/avatar/customization/Earring_03.png",
    url: "/models/avatar/customization/Earring.003.glb",
    lockedGroups: null,
  },
  {
    groupId: "12",
    name: "Earring_04",
    thumbnail: "/images/avatar/customization/Earring_04.png",
    url: "/models/avatar/customization/Earring.004.glb",
    lockedGroups: null,
  },
  {
    groupId: "12",
    name: "Bow_01",
    thumbnail: "/images/avatar/customization/Bow_01.png",
    url: "/models/avatar/customization/Bow.001.glb",
    lockedGroups: null,
  },
];
