import Buffalo from "../models/Buffalo";
import Cat from "../models/Cat";
import Chicken from "../models/Chicken";
import Cow from "../models/Cow";
import Deer from "../models/Deer";
import Dog from "../models/Dog";
import Duck from "../models/Duck";
import Elephant from "../models/Elephant";
import Frog from "../models/Frog";
import Giraffe from "../models/Giraffe";
import Horse from "../models/Horse";
import Lion from "../models/Lion";
import Mouse from "../models/Mouse";
import Pig from "../models/Pig";
import Rabbit from "../models/Rabbit";
import Sheep from "../models/Sheep";

export const words = [
  {
    type: "animals",
    indonesian: "sapi",
    english: "cow",
    ngoko: "sapi",
    madya: "lembu",
    alus: "lembu",
    ngokoSound: "/sounds/vocabularies/animals/sapi.mp3",
    madyaSound: "/sounds/vocabularies/animals/lembu.mp3",
    alusSound: "/sounds/vocabularies/animals/lembu.mp3",
    image: "/images/vocabularies/animals-cow.webp",
    model: <Cow scale={5} />,
    colliderSize: [0.7, 1.2, 2.4],
    colliderPosition: [0, 1.2, 0.9],
  },
  {
    type: "animals",
    indonesian: "ayam",
    english: "chicken",
    ngoko: "pitik",
    madya: "ayam",
    alus: "ayam",
    ngokoSound: "/sounds/vocabularies/animals/pitik.mp3",
    madyaSound: "/sounds/vocabularies/animals/ayam.mp3",
    alusSound: "/sounds/vocabularies/animals/ayam.mp3",
    image: "/images/vocabularies/animals-chicken.webp",
    model: <Chicken scale={0.003} />,
    colliderSize: [0.35, 0.5, 0.35],
    colliderPosition: [0, 0.5, 0],
  },
  {
    type: "animals",
    indonesian: "babi",
    english: "pig",
    ngoko: "celeng",
    madya: "andhapan",
    alus: "andhapan",
    ngokoSound: "/sounds/vocabularies/animals/celeng.mp3",
    madyaSound: "/sounds/vocabularies/animals/andhapan.mp3",
    alusSound: "/sounds/vocabularies/animals/andhapan.mp3",
    image: "/images/vocabularies/animals-pig.webp",
    model: <Pig scale={0.075} />,
    colliderSize: [0.4, 0.6, 1],
    colliderPosition: [0, 0.6, 0.2],
  },
  {
    type: "animals",
    indonesian: "singa",
    english: "lion",
    ngoko: "singo",
    madya: "singo",
    alus: "singo",
    ngokoSound: "/sounds/vocabularies/animals/singo.mp3",
    madyaSound: "/sounds/vocabularies/animals/singo.mp3",
    alusSound: "/sounds/vocabularies/animals/singo.mp3",
    image: "/images/vocabularies/animals-lion.webp",
    model: <Lion scale={0.9} />,
    colliderSize: [0.5, 1, 1.7],
    colliderPosition: [0, 1, 0.2],
  },
  {
    type: "animals",
    indonesian: "anjing",
    english: "dog",
    ngoko: "asu",
    madya: "segawon",
    alus: "segawon",
    ngokoSound: "/sounds/vocabularies/animals/asu.mp3",
    madyaSound: "/sounds/vocabularies/animals/segawon.mp3",
    alusSound: "/sounds/vocabularies/animals/segawon.mp3",
    image: "/images/vocabularies/animals-dog.webp",
    model: <Dog scale={0.5} />,
    colliderSize: [0.5, 0.6, 1.2],
    colliderPosition: [0, 0.6, 0],
  },
  {
    type: "animals",
    indonesian: "kucing",
    english: "cat",
    ngoko: "kucing",
    madya: "kucing",
    alus: "kucing",
    ngokoSound: "/sounds/vocabularies/animals/kucing.mp3",
    madyaSound: "/sounds/vocabularies/animals/kucing.mp3",
    alusSound: "/sounds/vocabularies/animals/kucing.mp3",
    image: "/images/vocabularies/animals-cat.webp",
    model: <Cat scale={2} />,
    colliderSize: [0.2, 0.3, 0.6],
    colliderPosition: [0, 0.3, 0],
  },
  {
    type: "animals",
    indonesian: "tikus",
    english: "mouse",
    ngoko: "tikus",
    madya: "tikus",
    alus: "tikus",
    ngokoSound: "/sounds/vocabularies/animals/tikus.mp3",
    madyaSound: "/sounds/vocabularies/animals/tikus.mp3",
    alusSound: "/sounds/vocabularies/animals/tikus.mp3",
    image: "/images/vocabularies/animals-mouse.webp",
    model: <Mouse scale={0.7} />,
    colliderSize: [0.1, 0.1, 0.35],
    colliderPosition: [0, 0, 0],
    rigidPositionY: 0.2,
  },
  {
    type: "animals",
    indonesian: "kuda",
    english: "horse",
    ngoko: "jaran",
    madya: "kapal",
    alus: "titihan",
    ngokoSound: "/sounds/vocabularies/animals/jaran.mp3",
    madyaSound: "/sounds/vocabularies/animals/kapal.mp3",
    alusSound: "/sounds/vocabularies/animals/titihan.mp3",
    image: "/images/vocabularies/animals-horse.webp",
    model: <Horse scale={0.6} />,
    colliderSize: [1.3, 1.2, 0.6],
    colliderPosition: [0.6, -0.5, 0],
    rigidPositionY: 1.75,
  },
  {
    type: "animals",
    indonesian: "bebek",
    english: "duck",
    ngoko: "itik",
    madya: "kambangan",
    alus: "kambangan",
    ngokoSound: "/sounds/vocabularies/animals/itik.mp3",
    madyaSound: "/sounds/vocabularies/animals/kambangan.mp3",
    alusSound: "/sounds/vocabularies/animals/kambangan.mp3",
    image: "/images/vocabularies/animals-duck.webp",
    model: <Duck scale={0.6} />,
    colliderSize: [0.4, 1.2, 0.8],
    colliderPosition: [0, 0, 0.2],
  },
  {
    type: "animals",
    indonesian: "gajah",
    english: "elephant",
    ngoko: "gajah",
    madya: "liman",
    alus: "liman",
    ngokoSound: "/sounds/vocabularies/animals/gajah.mp3",
    madyaSound: "/sounds/vocabularies/animals/liman.mp3",
    alusSound: "/sounds/vocabularies/animals/liman.mp3",
    image: "/images/vocabularies/animals-elephant.webp",
    model: <Elephant scale={2} />,
    colliderSize: [1, 4.6, 3.8],
    colliderPosition: [0, 0, 1.5],
  },
  {
    type: "animals",
    indonesian: "jerapah",
    english: "giraffe",
    ngoko: "jerapah",
    madya: "jerapah",
    alus: "jerapah",
    ngokoSound: "/sounds/vocabularies/animals/jerapah.mp3",
    madyaSound: "/sounds/vocabularies/animals/jerapah.mp3",
    alusSound: "/sounds/vocabularies/animals/jerapah.mp3",
    image: "/images/vocabularies/animals-giraffe.webp",
    model: <Giraffe scale={1.75} />,
    colliderSize: [0.7, 4.5, 1.1],
    colliderPosition: [0, 0, -1],
  },
  {
    type: "animals",
    indonesian: "domba",
    english: "sheep",
    ngoko: "wedhus",
    madya: "menda",
    alus: "menda",
    ngokoSound: "/sounds/vocabularies/animals/wedhus.mp3",
    madyaSound: "/sounds/vocabularies/animals/menda.mp3",
    alusSound: "/sounds/vocabularies/animals/menda.mp3",
    image: "/images/vocabularies/animals-sheep.webp",
    model: <Sheep scale={0.3} />,
    colliderSize: [0.4, 1.5, 1.1],
    colliderPosition: [0, 0, 0.3],
  },
  {
    type: "animals",
    indonesian: "kelinci",
    english: "rabbit",
    ngoko: "terwelu",
    madya: "terwelu",
    alus: "terwelu",
    ngokoSound: "/sounds/vocabularies/animals/terwelu.mp3",
    madyaSound: "/sounds/vocabularies/animals/terwelu.mp3",
    alusSound: "/sounds/vocabularies/animals/terwelu.mp3",
    image: "/images/vocabularies/animals-rabbit.webp",
    model: <Rabbit scale={0.3} />,
    colliderSize: [0.2, 0.45, 0.2],
    colliderPosition: [0, 0, 0],
    rigidPositionY: 0.22,
  },
  {
    type: "animals",
    indonesian: "katak",
    english: "frog",
    ngoko: "kodhok",
    madya: "kodhok",
    alus: "kodhok",
    ngokoSound: "/sounds/vocabularies/animals/kodhok.mp3",
    madyaSound: "/sounds/vocabularies/animals/kodhok.mp3",
    alusSound: "/sounds/vocabularies/animals/kodhok.mp3",
    image: "/images/vocabularies/animals-frog.webp",
    model: <Frog scale={1} />,
    colliderSize: [0.1, 0.25, 0.15],
    colliderPosition: [0, 0, 0.05],
  },
  {
    type: "animals",
    indonesian: "rusa",
    english: "deer",
    ngoko: "menjangan",
    madya: "sangsam",
    alus: "sangsam",
    ngokoSound: "/sounds/vocabularies/animals/menjangan.mp3",
    madyaSound: "/sounds/vocabularies/animals/sangsam.mp3",
    alusSound: "/sounds/vocabularies/animals/sangsam.mp3",
    image: "/images/vocabularies/animals-deer.webp",
    model: <Deer scale={0.5} />,
    colliderSize: [0.3, 1.5, 1.2],
    colliderPosition: [0, 0, 0.3],
  },
  {
    type: "animals",
    indonesian: "kerbau",
    english: "buffalo",
    ngoko: "kebo",
    madya: "mahesa",
    alus: "mahesa",
    ngokoSound: "/sounds/vocabularies/animals/kebo.mp3",
    madyaSound: "/sounds/vocabularies/animals/mahesa.mp3",
    alusSound: "/sounds/vocabularies/animals/mahesa.mp3",
    image: "/images/vocabularies/animals-buffalo.webp",
    model: <Buffalo scale={0.38} />,
    colliderSize: [0.45, 2.6, 2.3],
    colliderPosition: [0, 0, 0.75],
  },
];

export const positions = [
  {
    position: [0, 0, -18],
  },
  {
    position: [5, 0, -18],
  },
  {
    position: [10, 0, -18],
  },
  {
    position: [-5, 0, -18],
  },
  {
    position: [-10, 0, -18],
  },
  {
    position: [0, 0, -12],
  },
  {
    position: [5, 0, -12],
  },
  {
    position: [10, 0, -12],
  },
  {
    position: [-5, 0, -12],
  },
  {
    position: [-10, 0, -12],
  },
  {
    position: [5, 0, -6],
  },
  {
    position: [10, 0, -6],
  },
  {
    position: [0, 0, -6],
  },
  {
    position: [-5, 0, -6],
  },
  {
    position: [-10, 0, -6],
  },
  {
    position: [0, 0, 0],
  },
  {
    position: [5, 0, 0],
  },
  {
    position: [10, 0, 0],
  },
];
