/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/environment/fences.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials['wood.001']}
        position={[-18.85, 1.145, -9.711]}
        rotation={[Math.PI, -1.541, Math.PI]}
        scale={[5.374, 5.179, 5.374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials['wood.001']}
        position={[18.577, 1.145, 8.315]}
        rotation={[0, 1.541, 0]}
        scale={[5.374, 5.179, 5.374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials['wood.001']}
        position={[-3.788, 1.047, -39.81]}
        rotation={[-Math.PI, 0.03, -Math.PI]}
        scale={[5.374, 5.179, 5.374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials['wood.001']}
        position={[4.09, 1.047, 39]}
        rotation={[0, -0.03, 0]}
        scale={[5.374, 5.179, 5.374]}
      />
    </group>
  )
}

useGLTF.preload('./models/environment/fences.glb')