/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function PineTree(props) {
  const { nodes, materials } = useGLTF('./models/environment/pine-tree.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[4.395, 1.973, 2.978]} rotation={[Math.PI / 2, 0, -2.404]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials['Material.005']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/environment/pine-tree.glb')
