/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Tree01(props) {
  const { nodes, materials } = useGLTF('./models/environment/tree01.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.018]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, -0.357]} scale={90.444}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.AppleTree_MaterialApple001_0.geometry}
              material={materials['MaterialApple.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.AppleTree_MaterialAppleTree001_0.geometry}
              material={materials['MaterialAppleTree.001']}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/environment/tree01.glb')