export const words = [
    { 
        indonesian: 'merah', 
        ngoko: 'abang', 
        madya: 'abrit', 
        alus: 'kirmizi',
        soundNgoko: '',
        soundMadya: '',
        soundAlus: '',
        imagePath: '',
        hexColor: '#ff0000',
    },
    { 
        indonesian: 'hijau', 
        ngoko: 'ijo', 
        madya: 'hejo', 
        alus: 'miro',
        soundNgoko: '',
        soundMadya: '',
        soundAlus: '',
        imagePath: '',
        hexColor: '#09db09',
    },
    { 
        indonesian: 'biru', 
        ngoko: 'biru', 
        madya: 'wungu', 
        alus: 'nila',
        soundNgoko: '',
        soundMadya: '',
        soundAlus: '',
        imagePath: '',
        hexColor: '#0000ff',
    },
    { 
        indonesian: 'kuning', 
        ngoko: 'kuning', 
        madya: 'koneng', 
        alus: 'wars',
        soundNgoko: '',
        soundMadya: '',
        soundAlus: '',
        imagePath: '',
        hexColor: '#FFFF00',
    },
    { 
        indonesian: 'ungu', 
        ngoko: 'ungu', 
        madya: 'tarung', 
        alus: 'tarung',
        soundNgoko: '',
        soundMadya: '',
        soundAlus: '',
        imagePath: '',
        hexColor: '#A020F0',
    },
    { 
        indonesian: 'hitam', 
        ngoko: 'ireng', 
        madya: 'cemeng', 
        alus: 'wulung',
        soundNgoko: '',
        soundMadya: '',
        soundAlus: '',
        imagePath: '',
        hexColor: '#000000',
    },
    { 
        indonesian: 'putih', 
        ngoko: 'putih', 
        madya: 'bodas', 
        alus: 'padhang',
        soundNgoko: '',
        soundMadya: '',
        soundAlus: '',
        imagePath: '',
        hexColor: '#FFFFFF',
    },
    { 
        indonesian: 'coklat', 
        ngoko: 'coklat', 
        madya: 'coklat', 
        alus: 'samin',
        soundNgoko: '',
        soundMadya: '',
        soundAlus: '',
        imagePath: '',
        hexColor: '#8B4513',
    },
    { 
        indonesian: 'abu-abu', 
        ngoko: 'abu-abu', 
        madya: 'kelabu', 
        alus: 'kimpul',
        soundNgoko: '',
        soundMadya: '',
        soundAlus: '',
        imagePath: '',
        hexColor: '#808080',
    },
    { 
        indonesian: 'jingga', 
        ngoko: 'oranye', 
        madya: 'wungu', 
        alus: 'ginggang',
        soundNgoko: '',
        soundMadya: '',
        soundAlus: '',
        imagePath: '',
        hexColor: '#ff7e05',
    },
    { 
        indonesian: 'merah muda', 
        ngoko: 'jambu', 
        madya: 'jambu', 
        alus: 'rosa',
        soundNgoko: '',
        soundMadya: '',
        soundAlus: '',
        imagePath: '',
        hexColor: '#ff8ca0',
    },
    { 
        indonesian: 'biru muda', 
        ngoko: 'biru enom', 
        madya: 'biru enom', 
        alus: 'biru enom',
        soundNgoko: '',
        soundMadya: '',
        soundAlus: '',
        imagePath: '',
        hexColor: '#1cb3ff',
    },
    { 
        indonesian: 'hijau muda', 
        ngoko: 'ijo enom', 
        madya: 'ijo enom', 
        alus: 'ijo enom',
        soundNgoko: '',
        soundMadya: '',
        soundAlus: '',
        imagePath: '',
        hexColor: '#66ff66',
    },
];
