export const words = [
  {
    type: "colors",
    indonesian: "merah",
    english: "red",
    ngoko: "abang",
    madya: "abrit",
    alus: "kirmizi",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    imagePath: "",
    hexColor: "#ff0000",
  },
  {
    type: "colors",
    indonesian: "hijau",
    english: "green",
    ngoko: "ijo",
    madya: "hejo",
    alus: "miro",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    imagePath: "",
    hexColor: "#09db09",
  },
  {
    type: "colors",
    indonesian: "biru",
    english: "blue",
    ngoko: "biru",
    madya: "wungu",
    alus: "nila",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    imagePath: "",
    hexColor: "#0000ff",
  },
  {
    type: "colors",
    indonesian: "kuning",
    english: "yellow",
    ngoko: "kuning",
    madya: "koneng",
    alus: "wars",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    imagePath: "",
    hexColor: "#FFFF00",
  },
  {
    type: "colors",
    indonesian: "ungu",
    english: "purple",
    ngoko: "ungu",
    madya: "tarung",
    alus: "tarung",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    imagePath: "",
    hexColor: "#A020F0",
  },
  {
    type: "colors",
    indonesian: "hitam",
    english: "black",
    ngoko: "ireng",
    madya: "cemeng",
    alus: "wulung",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    imagePath: "",
    hexColor: "#000000",
  },
  {
    type: "colors",
    indonesian: "putih",
    english: "white",
    ngoko: "putih",
    madya: "bodas",
    alus: "padhang",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    imagePath: "",
    hexColor: "#FFFFFF",
  },
  {
    type: "colors",
    indonesian: "coklat",
    english: "brown",
    ngoko: "coklat",
    madya: "coklat",
    alus: "samin",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    imagePath: "",
    hexColor: "#8B4513",
  },
  {
    type: "colors",
    indonesian: "abu-abu",
    english: "gray",
    ngoko: "abu-abu",
    madya: "kelabu",
    alus: "kimpul",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    imagePath: "",
    hexColor: "#808080",
  },
  {
    type: "colors",
    indonesian: "jingga",
    english: "orange",
    ngoko: "oranye",
    madya: "wungu",
    alus: "ginggang",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    imagePath: "",
    hexColor: "#ff7e05",
  },
  {
    type: "colors",
    indonesian: "merah muda",
    english: "pink",
    ngoko: "jambu",
    madya: "jambu",
    alus: "rosa",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    imagePath: "",
    hexColor: "#ff8ca0",
  },
  {
    type: "colors",
    indonesian: "biru muda",
    english: "light blue",
    ngoko: "biru enom",
    madya: "biru enom",
    alus: "biru enom",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    imagePath: "",
    hexColor: "#1cb3ff",
  },
  {
    type: "colors",
    indonesian: "hijau muda",
    english: "light green",
    ngoko: "ijo enom",
    madya: "ijo enom",
    alus: "ijo enom",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    imagePath: "",
    hexColor: "#77fc77",
  },
];
