export const words = [
  {
    type: "colors",
    indonesian: "merah",
    english: "red",
    ngoko: "abang",
    madya: "abrit",
    alus: "abrit",
    ngokoSound: "/sounds/vocabularies/colors/abang.mp3",
    madyaSound: "/sounds/vocabularies/colors/abrit.mp3",
    alusSound: "/sounds/vocabularies/colors/abrit.mp3",
    hexColor: "#ff0000",
  },
  {
    type: "colors",
    indonesian: "hijau",
    english: "green",
    ngoko: "ijo",
    madya: "hejo",
    alus: "ijem",
    ngokoSound: "/sounds/vocabularies/colors/ijo.mp3",
    madyaSound: "/sounds/vocabularies/colors/hejo.mp3",
    alusSound: "/sounds/vocabularies/colors/ijem.mp3",
    hexColor: "#09db09",
  },
  {
    type: "colors",
    indonesian: "biru",
    english: "blue",
    ngoko: "biru",
    madya: "biru",
    alus: "biru",
    ngokoSound: "/sounds/vocabularies/colors/biru.mp3",
    madyaSound: "/sounds/vocabularies/colors/biru.mp3",
    alusSound: "/sounds/vocabularies/colors/biru.mp3",
    hexColor: "#0000ff",
  },
  {
    type: "colors",
    indonesian: "kuning",
    english: "yellow",
    ngoko: "kuning",
    madya: "koneng",
    alus: "jenar",
    ngokoSound: "/sounds/vocabularies/colors/kuning.mp3",
    madyaSound: "/sounds/vocabularies/colors/koneng.mp3",
    alusSound: "/sounds/vocabularies/colors/jenar.mp3",
    hexColor: "#FFFF00",
  },
  {
    type: "colors",
    indonesian: "ungu",
    english: "purple",
    ngoko: "ungu",
    madya: "ungu",
    alus: "ungu",
    ngokoSound: "/sounds/vocabularies/colors/ungu.mp3",
    madyaSound: "/sounds/vocabularies/colors/ungu.mp3",
    alusSound: "/sounds/vocabularies/colors/ungu.mp3",
    hexColor: "#A020F0",
  },
  {
    type: "colors",
    indonesian: "hitam",
    english: "black",
    ngoko: "ireng",
    madya: "cemeng",
    alus: "wulung",
    ngokoSound: "/sounds/vocabularies/colors/ireng.mp3",
    madyaSound: "/sounds/vocabularies/colors/cemeng.mp3",
    alusSound: "/sounds/vocabularies/colors/wulung.mp3",
    hexColor: "#000000",
  },
  {
    type: "colors",
    indonesian: "putih",
    english: "white",
    ngoko: "putih",
    madya: "pethak",
    alus: "padhang",
    ngokoSound: "/sounds/vocabularies/colors/putih.mp3",
    madyaSound: "/sounds/vocabularies/colors/pethak.mp3",
    alusSound: "/sounds/vocabularies/colors/padhang.mp3",
    hexColor: "#FFFFFF",
  },
  {
    type: "colors",
    indonesian: "coklat",
    english: "brown",
    ngoko: "soklat",
    madya: "soklat",
    alus: "soklat",
    ngokoSound: "/sounds/vocabularies/colors/soklat.mp3",
    madyaSound: "/sounds/vocabularies/colors/soklat.mp3",
    alusSound: "/sounds/vocabularies/colors/soklat.mp3",
    hexColor: "#8B4513",
  },
  {
    type: "colors",
    indonesian: "abu-abu",
    english: "gray",
    ngoko: "klawu",
    madya: "klawu",
    alus: "klawu",
    ngokoSound: "/sounds/vocabularies/colors/klawu.mp3",
    madyaSound: "/sounds/vocabularies/colors/klawu.mp3",
    alusSound: "/sounds/vocabularies/colors/klawu.mp3",
    hexColor: "#808080",
  },
  {
    type: "colors",
    indonesian: "jingga",
    english: "orange",
    ngoko: "oren",
    madya: "oren",
    alus: "oren",
    ngokoSound: "/sounds/vocabularies/colors/oren.mp3",
    madyaSound: "/sounds/vocabularies/colors/oren.mp3",
    alusSound: "/sounds/vocabularies/colors/oren.mp3",
    hexColor: "#ff7e05",
  },
  {
    type: "colors",
    indonesian: "merah muda",
    english: "pink",
    ngoko: "jambu",
    madya: "jambu",
    alus: "jambu",
    ngokoSound: "/sounds/vocabularies/colors/jambu.mp3",
    madyaSound: "/sounds/vocabularies/colors/jambu.mp3",
    alusSound: "/sounds/vocabularies/colors/jambu.mp3",
    hexColor: "#ff8ca0",
  },
];
