export const words = [
  {
    type: "body-parts",
    indonesian: "mata",
    english: "eye",
    ngoko: "moto",
    madya: "mripat",
    alus: "soca",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-eye.jpg",
    position: [0.85, 7.7, 1.1],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "rambut",
    english: "hair",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-hair.jpg",
    position: [0.85, 9, 1.4],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "dahi",
    english: "forehead",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-forehead.jpg",
    position: [-0.1, 8.5, 1.5],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "alis",
    english: "eyebrow",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-eyebrow.jpg",
    position: [0.7, 8.2, 1.3],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "hidung",
    english: "nose",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-nose.jpg",
    position: [-0.1, 7.2, 1.5],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "mulut",
    english: "mouth",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-mouth.jpg",
    position: [0.25, 6.75, 1.4],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "pipi",
    english: "cheek",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-cheek.jpg",
    position: [-0.85, 6.9, 1.1],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "dagu",
    english: "chin",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-chin.jpg",
    position: [-0.1, 6.45, 1.3],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "telinga",
    english: "ear",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-ear.jpg",
    position: [-1.5, 7.5, 0],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "dada",
    english: "chest",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-chest.jpg",
    position: [-0.1, 5.9, 0.85],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "perut",
    english: "stomach",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-stomach.jpg",
    position: [-0.1, 4.3, 1.2],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "punggung",
    english: "back",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-back.jpg",
    position: [0, 5.3, -0.65],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "tangan",
    english: "hand",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-hand.jpg",
    position: [2.5, 5.9, 0.5],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "jari",
    english: "finger",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-finger.jpg",
    position: [4.3, 5.9, 0],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "paha",
    english: "thigh",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-thigh.jpg",
    position: [-0.7, 2.3, 0.72],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "kaki",
    english: "leg",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-leg.jpg",
    position: [-0.7, 0.75, 0.72],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "pundak",
    english: "shoulder",
    ngoko: "abc",
    madya: "ab",
    alus: "a",
    soundNgoko: "",
    soundMadya: "",
    soundAlus: "",
    image: "/images/vocabularies/body-parts-shoulder.jpg",
    position: [-1.2, 6.4, 0],
    visible: false,
    isCorrect: false,
  },
];
