export const words = [
  {
    type: "body-parts",
    indonesian: "mata",
    english: "eye",
    ngoko: "mripat",
    madya: "paningal",
    alus: "soca",
    ngokoSound: "/sounds/vocabularies/body-parts/mripat.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/paningal.mp3",
    alusSound: "/sounds/vocabularies/body-parts/soca.mp3",
    image: "/images/vocabularies/body-parts-eye.webp",
    position: [0.85, 7.7, 1.1],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "rambut",
    english: "hair",
    ngoko: "rambut",
    madya: "rambut",
    alus: "rikma",
    ngokoSound: "/sounds/vocabularies/body-parts/rambut.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/rambut.mp3",
    alusSound: "/sounds/vocabularies/body-parts/rikma.mp3",
    image: "/images/vocabularies/body-parts-hair.webp",
    position: [0.85, 9, 1.4],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "dahi",
    english: "forehead",
    ngoko: "bathuk",
    madya: "bathuk",
    alus: "palarapan",
    ngokoSound: "/sounds/vocabularies/body-parts/bathuk.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/bathuk.mp3",
    alusSound: "/sounds/vocabularies/body-parts/palarapan.mp3",
    image: "/images/vocabularies/body-parts-forehead.webp",
    position: [-0.1, 8.5, 1.5],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "alis",
    english: "eyebrow",
    ngoko: "alis",
    madya: "alis",
    alus: "imba",
    ngokoSound: "/sounds/vocabularies/body-parts/alis.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/alis.mp3",
    alusSound: "/sounds/vocabularies/body-parts/imba.mp3",
    image: "/images/vocabularies/body-parts-eyebrow.webp",
    position: [0.7, 8.2, 1.3],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "hidung",
    english: "nose",
    ngoko: "irung",
    madya: "irung",
    alus: "grana",
    ngokoSound: "/sounds/vocabularies/body-parts/irung.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/irung.mp3",
    alusSound: "/sounds/vocabularies/body-parts/grana.mp3",
    image: "/images/vocabularies/body-parts-nose.webp",
    position: [-0.1, 7.2, 1.5],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "mulut",
    english: "mouth",
    ngoko: "cangkem",
    madya: "cangkem",
    alus: "tutuk",
    ngokoSound: "/sounds/vocabularies/body-parts/cangkem.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/cangkem.mp3",
    alusSound: "/sounds/vocabularies/body-parts/tutuk.mp3",
    image: "/images/vocabularies/body-parts-mouth.webp",
    position: [0.25, 6.75, 1.4],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "pipi",
    english: "cheek",
    ngoko: "pipi",
    madya: "pipi",
    alus: "pangarasan",
    ngokoSound: "/sounds/vocabularies/body-parts/pipi.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/pipi.mp3",
    alusSound: "/sounds/vocabularies/body-parts/pangarasan.mp3",
    image: "/images/vocabularies/body-parts-cheek.webp",
    position: [-0.85, 6.9, 1.1],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "dagu",
    english: "chin",
    ngoko: "janggut",
    madya: "janggut",
    alus: "kethekan",
    ngokoSound: "/sounds/vocabularies/body-parts/janggut.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/janggut.mp3",
    alusSound: "/sounds/vocabularies/body-parts/kethekan.mp3",
    image: "/images/vocabularies/body-parts-chin.webp",
    position: [-0.1, 6.45, 1.3],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "telinga",
    english: "ear",
    ngoko: "kuping",
    madya: "kuping",
    alus: "talingan",
    ngokoSound: "/sounds/vocabularies/body-parts/kuping.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/kuping.mp3",
    alusSound: "/sounds/vocabularies/body-parts/talingan.mp3",
    image: "/images/vocabularies/body-parts-ear.webp",
    position: [-1.5, 7.5, 0],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "leher",
    english: "neck",
    ngoko: "gulu",
    madya: "gulu",
    alus: "jangga",
    ngokoSound: "/sounds/vocabularies/body-parts/gulu.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/gulu.mp3",
    alusSound: "/sounds/vocabularies/body-parts/jangga.mp3",
    image: "/images/vocabularies/body-parts-neck.webp",
    position: [-0.1, 6.2, 0.7],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "pundak",
    english: "shoulder",
    ngoko: "pundhak",
    madya: "pundhak",
    alus: "pamidhangan",
    ngokoSound: "/sounds/vocabularies/body-parts/pundhak.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/pundhak.mp3",
    alusSound: "/sounds/vocabularies/body-parts/pamidhangan.mp3",
    image: "/images/vocabularies/body-parts-shoulder.webp",
    position: [-1.2, 6.4, 0],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "dada",
    english: "chest",
    ngoko: "dhadha",
    madya: "dhadha",
    alus: "jaja",
    ngokoSound: "/sounds/vocabularies/body-parts/dhadha.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/dhadha.mp3",
    alusSound: "/sounds/vocabularies/body-parts/jaja.mp3",
    image: "/images/vocabularies/body-parts-chest.webp",
    position: [-0.1, 5.7, 0.95],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "perut",
    english: "stomach",
    ngoko: "weteng",
    madya: "weteng",
    alus: "padharan",
    ngokoSound: "/sounds/vocabularies/body-parts/weteng.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/weteng.mp3",
    alusSound: "/sounds/vocabularies/body-parts/padharan.mp3",
    image: "/images/vocabularies/body-parts-stomach.webp",
    position: [-0.1, 4.3, 1.2],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "punggung",
    english: "back",
    ngoko: "geger",
    madya: "geger",
    alus: "pengkeran",
    ngokoSound: "/sounds/vocabularies/body-parts/geger.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/geger.mp3",
    alusSound: "/sounds/vocabularies/body-parts/pengkeran.mp3",
    image: "/images/vocabularies/body-parts-back.webp",
    position: [0, 5.3, -0.65],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "tangan",
    english: "hand",
    ngoko: "tangan",
    madya: "tangan",
    alus: "asta",
    ngokoSound: "/sounds/vocabularies/body-parts/tangan.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/tangan.mp3",
    alusSound: "/sounds/vocabularies/body-parts/asta.mp3",
    image: "/images/vocabularies/body-parts-hand.webp",
    position: [2.5, 5.9, 0.5],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "jari",
    english: "finger",
    ngoko: "driji",
    madya: "driji",
    alus: "racikan",
    ngokoSound: "/sounds/vocabularies/body-parts/driji.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/driji.mp3",
    alusSound: "/sounds/vocabularies/body-parts/racikan.mp3",
    image: "/images/vocabularies/body-parts-finger.webp",
    position: [4.3, 5.9, 0],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "paha",
    english: "thigh",
    ngoko: "pupu",
    madya: "pupu",
    alus: "wenthis",
    ngokoSound: "/sounds/vocabularies/body-parts/pupu.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/pupu.mp3",
    alusSound: "/sounds/vocabularies/body-parts/wenthis.mp3",
    image: "/images/vocabularies/body-parts-thigh.webp",
    position: [-0.7, 2.3, 0.72],
    visible: false,
    isCorrect: false,
  },
  {
    type: "body-parts",
    indonesian: "kaki",
    english: "leg",
    ngoko: "sikil",
    madya: "suku",
    alus: "ampeyan",
    ngokoSound: "/sounds/vocabularies/body-parts/sikil.mp3",
    madyaSound: "/sounds/vocabularies/body-parts/suku.mp3",
    alusSound: "/sounds/vocabularies/body-parts/ampeyan.mp3",
    image: "/images/vocabularies/body-parts-leg.webp",
    position: [-0.7, 0.75, 0.72],
    visible: false,
    isCorrect: false,
  },
];
