/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Safat_Rules (https://sketchfab.com/Safat_Rules)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/football-89ce97755fe9499aa59cb0876c21ee86
Title: Football
*/

import { useGLTF } from "@react-three/drei";

export default function Football(props) {
  const { nodes, materials } = useGLTF("/models/environment/football.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/environment/football.glb");
