export const words = [
  { english: "1", ngoko: "siji", madya: "setunggal", alus: "setunggal" },
  { english: "2", ngoko: "loro", madya: "kalih", alus: "kalih" },
  { english: "3", ngoko: "telu", madya: "tiga", alus: "tiga" },
  { english: "4", ngoko: "papat", madya: "sekawan", alus: "sekawan" },
  { english: "5", ngoko: "lima", madya: "gangsal", alus: "gangsal" },
  { english: "6", ngoko: "enem", madya: "enem", alus: "enem" },
  { english: "7", ngoko: "pitu", madya: "pitu", alus: "pitu" },
  { english: "8", ngoko: "wolu", madya: "wolu", alus: "wolu" },
  { english: "9", ngoko: "sanga", madya: "sanga", alus: "sanga" },
  { english: "10", ngoko: "sepuluh", madya: "sedasa", alus: "sedasa" },
  { english: "11", ngoko: "sewelas", madya: "sewelas", alus: "sewelas" },
  { english: "12", ngoko: "rolas", madya: "kalih welas", alus: "kalih welas" },
  { english: "13", ngoko: "telulas", madya: "tiga welas", alus: "tiga welas" },
  {
    english: "14",
    ngoko: "patbelas",
    madya: "sekawan welas",
    alus: "sekawan welas",
  },
  {
    english: "15",
    ngoko: "limalas",
    madya: "gangsal welas",
    alus: "gangsal welas",
  },
  { english: "16", ngoko: "nembelas", madya: "enem welas", alus: "enem welas" },
  { english: "17", ngoko: "pitulas", madya: "pitulas", alus: "pitulas" },
  { english: "18", ngoko: "wolulas", madya: "wolulas", alus: "wolulas" },
  { english: "19", ngoko: "sangalas", madya: "sangalas", alus: "sangalas" },
  {
    english: "20",
    ngoko: "rong puluh",
    madya: "kalih dasa",
    alus: "kalih dasa",
  },
  { english: "21", ngoko: "selikur", madya: "selikur", alus: "selikur" },
  {
    english: "22",
    ngoko: "rolikur",
    madya: "kalih likur",
    alus: "kalih likur",
  },
  {
    english: "23",
    ngoko: "telulikur",
    madya: "tigang likur",
    alus: "tigang likur",
  },
  {
    english: "24",
    ngoko: "patlikur",
    madya: "sekawan likur",
    alus: "sekawan likur",
  },
  { english: "25", ngoko: "selawe", madya: "selangkung", alus: "selangkung" },
  { english: "26", ngoko: "nemlikur", madya: "nemlikur", alus: "nemlikur" },
  { english: "27", ngoko: "pitulikur", madya: "pitulikur", alus: "pitulikur" },
  { english: "28", ngoko: "wolulikur", madya: "wolulikur", alus: "wolulikur" },
  {
    english: "29",
    ngoko: "sanga likur",
    madya: "sangalikur",
    alus: "sangalikur",
  },
  {
    english: "30",
    ngoko: "telung puluh",
    madya: "tigang dasa",
    alus: "tigang dasa",
  },
  {
    english: "31",
    ngoko: "telung puluh siji",
    madya: "tigang dasa setunggal",
    alus: "tigang dasa setunggal",
  },
  {
    english: "32",
    ngoko: "telung puluh loro",
    madya: "tigang dasa kalih",
    alus: "tigang dasa kalih",
  },
  {
    english: "33",
    ngoko: "telung puluh telu",
    madya: "tigang dasa tiga",
    alus: "tigang dasa tiga",
  },
  {
    english: "34",
    ngoko: "telung puluh papat",
    madya: "tigang dasa sekawan",
    alus: "tigang dasa sekawan",
  },
  {
    english: "35",
    ngoko: "telung puluh lima",
    madya: "tigang dasa gangsal",
    alus: "tigang dasa gangsal",
  },
  {
    english: "36",
    ngoko: "telung puluh enem",
    madya: "tigang dasa enem",
    alus: "tigang dasa enem",
  },
  {
    english: "37",
    ngoko: "telung puluh pitu",
    madya: "tigang dasa pitu",
    alus: "tigang dasa pitu",
  },
  {
    english: "38",
    ngoko: "telung puluh wolu",
    madya: "tigang dasa wolu",
    alus: "tigang dasa wolu",
  },
  {
    english: "39",
    ngoko: "telung puluh sanga",
    madya: "tigang dasa sanga",
    alus: "tigang dasa sanga",
  },
  {
    english: "40",
    ngoko: "patang puluh",
    madya: "sekawan dasa",
    alus: "sekawan dasa",
  },
  {
    english: "41",
    ngoko: "patang puluh siji",
    madya: "sekawan dasa setunggal",
    alus: "sekawan dasa setunggal",
  },
  {
    english: "42",
    ngoko: "patang puluh loro",
    madya: "sekawan dasa kalih",
    alus: "sekawan dasa kalih",
  },
  {
    english: "43",
    ngoko: "patang puluh telu",
    madya: "sekawan dasa tiga",
    alus: "sekawan dasa tiga",
  },
  {
    english: "44",
    ngoko: "patang puluh papat",
    madya: "sekawan dasa sekawan",
    alus: "sekawan dasa sekawan",
  },
  {
    english: "45",
    ngoko: "patang puluh lima",
    madya: "sekawan dasa gangsal",
    alus: "sekawan dasa gangsal",
  },
  {
    english: "46",
    ngoko: "patang puluh enem",
    madya: "sekawan dasa enem",
    alus: "sekawan dasa enem",
  },
  {
    english: "47",
    ngoko: "patang puluh pitu",
    madya: "sekawan dasa pitu",
    alus: "sekawan dasa pitu",
  },
  {
    english: "48",
    ngoko: "patang puluh wolu",
    madya: "sekawan dasa wolu",
    alus: "sekawan dasa wolu",
  },
  {
    english: "49",
    ngoko: "patang puluh sanga",
    madya: "sekawan dasa sanga",
    alus: "sekawan dasa sanga",
  },
  { english: "50", ngoko: "seket", madya: "seket", alus: "seket" },
  {
    english: "51",
    ngoko: "seket siji",
    madya: "seket setunggal",
    alus: "seket setunggal",
  },
  {
    english: "52",
    ngoko: "seket loro",
    madya: "seket kalih",
    alus: "seket kalih",
  },
  {
    english: "53",
    ngoko: "seket telu",
    madya: "seket tiga",
    alus: "seket tiga",
  },
  {
    english: "54",
    ngoko: "seket papat",
    madya: "seket sekawan",
    alus: "seket sekawan",
  },
  {
    english: "55",
    ngoko: "seket lima",
    madya: "seket gangsal",
    alus: "seket gangsal",
  },
  {
    english: "56",
    ngoko: "seket enem",
    madya: "seket enem",
    alus: "seket enem",
  },
  {
    english: "57",
    ngoko: "seket pitu",
    madya: "seket pitu",
    alus: "seket pitu",
  },
  {
    english: "58",
    ngoko: "seket wolu",
    madya: "seket wolu",
    alus: "seket wolu",
  },
  {
    english: "59",
    ngoko: "seket sanga",
    madya: "seket sanga",
    alus: "seket sanga",
  },
  { english: "60", ngoko: "sewidak", madya: "sewidak", alus: "sewidak" },
  {
    english: "61",
    ngoko: "sewidak siji",
    madya: "sewidak setunggal",
    alus: "sewidak setunggal",
  },
  {
    english: "62",
    ngoko: "sewidak loro",
    madya: "sewidak kalih",
    alus: "sewidak kalih",
  },
  {
    english: "63",
    ngoko: "sewidak telu",
    madya: "sewidak tiga",
    alus: "sewidak tiga",
  },
  {
    english: "64",
    ngoko: "sewidak papat",
    madya: "sewidak sekawan",
    alus: "sewidak sekawan",
  },
  {
    english: "65",
    ngoko: "sewidak lima",
    madya: "sewidak gangsal",
    alus: "sewidak gangsal",
  },
  {
    english: "66",
    ngoko: "sewidak enem",
    madya: "sewidak enem",
    alus: "sewidak enem",
  },
  {
    english: "67",
    ngoko: "sewidak pitu",
    madya: "sewidak pitu",
    alus: "sewidak pitu",
  },
  {
    english: "68",
    ngoko: "sewidak wolu",
    madya: "sewidak wolu",
    alus: "sewidak wolu",
  },
  {
    english: "69",
    ngoko: "sewidak sanga",
    madya: "sewidak sanga",
    alus: "sewidak sanga",
  },
  {
    english: "70",
    ngoko: "pitung puluh",
    madya: "pitung dasa",
    alus: "pitung dasa",
  },
  {
    english: "71",
    ngoko: "pitung puluh siji",
    madya: "pitung dasa setunggal",
    alus: "pitung dasa setunggal",
  },
  {
    english: "72",
    ngoko: "pitung puluh loro",
    madya: "pitung dasa kalih",
    alus: "pitung dasa kalih",
  },
  {
    english: "73",
    ngoko: "pitung puluh telu",
    madya: "pitung dasa tiga",
    alus: "pitung dasa tiga",
  },
  {
    english: "74",
    ngoko: "pitung puluh papat",
    madya: "pitung dasa sekawan",
    alus: "pitung dasa sekawan",
  },
  {
    english: "75",
    ngoko: "pitung puluh lima",
    madya: "pitung dasa gangsal",
    alus: "pitung dasa gangsal",
  },
  {
    english: "76",
    ngoko: "pitung puluh enem",
    madya: "pitung dasa enem",
    alus: "pitung dasa enem",
  },
  {
    english: "77",
    ngoko: "pitung puluh pitu",
    madya: "pitung dasa pitu",
    alus: "pitung dasa pitu",
  },
  {
    english: "78",
    ngoko: "pitung puluh wolu",
    madya: "pitung dasa wolu",
    alus: "pitung dasa wolu",
  },
  {
    english: "79",
    ngoko: "pitung puluh sanga",
    madya: "pitung dasa sanga",
    alus: "pitung dasa sanga",
  },
  {
    english: "80",
    ngoko: "wolung puluh",
    madya: "wolung dasa",
    alus: "wolung dasa",
  },
  {
    english: "81",
    ngoko: "wolung puluh siji",
    madya: "wolung dasa setunggal",
    alus: "wolung dasa setunggal",
  },
  {
    english: "82",
    ngoko: "wolung puluh loro",
    madya: "wolung dasa kalih",
    alus: "wolung dasa kalih",
  },
  {
    english: "83",
    ngoko: "wolung puluh telu",
    madya: "wolung dasa tiga",
    alus: "wolung dasa tiga",
  },
  {
    english: "84",
    ngoko: "wolung puluh papat",
    madya: "wolung dasa sekawan",
    alus: "wolung dasa sekawan",
  },
  {
    english: "85",
    ngoko: "wolung puluh lima",
    madya: "wolung dasa gangsal",
    alus: "wolung dasa gangsal",
  },
  {
    english: "86",
    ngoko: "wolung puluh enem",
    madya: "wolung dasa enem",
    alus: "wolung dasa enem",
  },
  {
    english: "87",
    ngoko: "wolung puluh pitu",
    madya: "wolung dasa pitu",
    alus: "wolung dasa pitu",
  },
  {
    english: "88",
    ngoko: "wolung puluh wolu",
    madya: "wolung dasa wolu",
    alus: "wolung dasa wolu",
  },
  {
    english: "89",
    ngoko: "wolung puluh sanga",
    madya: "wolung dasa sanga",
    alus: "wolung dasa sanga",
  },
  {
    english: "90",
    ngoko: "sangang puluh",
    madya: "sangang dasa",
    alus: "sangang dasa",
  },
  {
    english: "91",
    ngoko: "sangang puluh siji",
    madya: "sangang dasa setunggal",
    alus: "sangang dasa setunggal",
  },
  {
    english: "92",
    ngoko: "sangang puluh loro",
    madya: "sangang dasa kalih",
    alus: "sangang dasa kalih",
  },
  {
    english: "93",
    ngoko: "sangang puluh telu",
    madya: "sangang dasa tiga",
    alus: "sangang dasa tiga",
  },
  {
    english: "94",
    ngoko: "sangang puluh papat",
    madya: "sangang dasa sekawan",
    alus: "sangang dasa sekawan",
  },
  {
    english: "95",
    ngoko: "sangang puluh lima",
    madya: "sangang dasa gangsal",
    alus: "sangang dasa gangsal",
  },
  {
    english: "96",
    ngoko: "sangang puluh enem",
    madya: "sangang dasa enem",
    alus: "sangang dasa enem",
  },
  {
    english: "97",
    ngoko: "sangang puluh pitu",
    madya: "sangang dasa pitu",
    alus: "sangang dasa pitu",
  },
  {
    english: "98",
    ngoko: "sangang puluh wolu",
    madya: "sangang dasa wolu",
    alus: "sangang dasa wolu",
  },
  {
    english: "99",
    ngoko: "sangang puluh sanga",
    madya: "sangang dasa sanga",
    alus: "sangang dasa sanga",
  },
  {
    english: "100",
    ngoko: "satus",
    madya: "setunggal atus",
    alus: "setunggal atus",
  },
]

export const positions = [
  {
    position: [0, 0, -15],
  },
  {
    position: [3, 0, -15],
  },
  {
    position: [6, 0, -15],
  },
  {
    position: [-3, 0, -15],
  },
  {
    position: [-6, 0, -15],
  },
  {
    position: [0, 0, -10],
  },
  {
    position: [3, 0, -10],
  },
  {
    position: [6, 0, -10],
  },
  {
    position: [-3, 0, -10],
  },
  {
    position: [-6, 0, -10],
  },
  {
    position: [3, 0, -5],
  },
  {
    position: [6, 0, -5],
  },
  {
    position: [-3, 0, -5],
  },
  {
    position: [-6, 0, -5],
  },
  {
    position: [0, 0, 0],
  },
  {
    position: [3, 0, 0],
  },
  {
    position: [6, 0, 0],
  },
  {
    position: [-3, 0, 0],
  },
  {
    position: [-6, 0, 0],
  },
]
