export const words = [
  {
    type: "numbers",
    english: "1",
    indonesian: "1",
    ngoko: "siji",
    madya: "setunggal",
    alus: "setunggal",
  },
  {
    type: "numbers",
    english: "2",
    indonesian: "2",
    ngoko: "loro",
    madya: "kalih",
    alus: "kalih",
  },
  {
    type: "numbers",
    english: "3",
    indonesian: "3",
    ngoko: "telu",
    madya: "tiga",
    alus: "tiga",
  },
  {
    type: "numbers",
    english: "4",
    indonesian: "4",
    ngoko: "papat",
    madya: "sekawan",
    alus: "sekawan",
  },
  {
    type: "numbers",
    english: "5",
    indonesian: "5",
    ngoko: "lima",
    madya: "gangsal",
    alus: "gangsal",
  },
  {
    type: "numbers",
    english: "6",
    indonesian: "6",
    ngoko: "enem",
    madya: "enem",
    alus: "enem",
  },
  {
    type: "numbers",
    english: "7",
    indonesian: "7",
    ngoko: "pitu",
    madya: "pitu",
    alus: "pitu",
  },
  {
    type: "numbers",
    english: "8",
    indonesian: "8",
    ngoko: "wolu",
    madya: "wolu",
    alus: "wolu",
  },
  {
    type: "numbers",
    english: "9",
    indonesian: "9",
    ngoko: "sanga",
    madya: "sanga",
    alus: "sanga",
  },
  {
    type: "numbers",
    english: "10",
    indonesian: "10",
    ngoko: "sepuluh",
    madya: "sedasa",
    alus: "sedasa",
  },
  {
    type: "numbers",
    english: "11",
    indonesian: "11",
    ngoko: "sewelas",
    madya: "sewelas",
    alus: "sewelas",
  },
  {
    type: "numbers",
    english: "12",
    indonesian: "12",
    ngoko: "rolas",
    madya: "kalih welas",
    alus: "kalih welas",
  },
  {
    type: "numbers",
    english: "13",
    indonesian: "13",
    ngoko: "telulas",
    madya: "tiga welas",
    alus: "tiga welas",
  },
  {
    type: "numbers",
    english: "14",
    indonesian: "14",
    ngoko: "patbelas",
    madya: "sekawan welas",
    alus: "sekawan welas",
  },
  {
    type: "numbers",
    english: "15",
    indonesian: "15",
    ngoko: "limalas",
    madya: "gangsal welas",
    alus: "gangsal welas",
  },
  {
    type: "numbers",
    english: "16",
    indonesian: "16",
    ngoko: "nembelas",
    madya: "enem welas",
    alus: "enem welas",
  },
  {
    type: "numbers",
    english: "17",
    indonesian: "17",
    ngoko: "pitulas",
    madya: "pitulas",
    alus: "pitulas",
  },
  {
    type: "numbers",
    english: "18",
    indonesian: "18",
    ngoko: "wolulas",
    madya: "wolulas",
    alus: "wolulas",
  },
  {
    type: "numbers",
    english: "19",
    indonesian: "19",
    ngoko: "sangalas",
    madya: "sangalas",
    alus: "sangalas",
  },
  {
    type: "numbers",
    english: "20",
    indonesian: "20",
    ngoko: "rong puluh",
    madya: "kalih dasa",
    alus: "kalih dasa",
  },
  {
    type: "numbers",
    english: "21",
    indonesian: "21",
    ngoko: "selikur",
    madya: "selikur",
    alus: "selikur",
  },
  {
    type: "numbers",
    english: "22",
    indonesian: "22",
    ngoko: "rolikur",
    madya: "kalih likur",
    alus: "kalih likur",
  },
  {
    type: "numbers",
    english: "23",
    indonesian: "23",
    ngoko: "telulikur",
    madya: "tigang likur",
    alus: "tigang likur",
  },
  {
    type: "numbers",
    english: "24",
    indonesian: "24",
    ngoko: "patlikur",
    madya: "sekawan likur",
    alus: "sekawan likur",
  },
  {
    type: "numbers",
    english: "25",
    indonesian: "25",
    ngoko: "selawe",
    madya: "selangkung",
    alus: "selangkung",
  },
  {
    type: "numbers",
    english: "26",
    indonesian: "26",
    ngoko: "nemlikur",
    madya: "nemlikur",
    alus: "nemlikur",
  },
  {
    type: "numbers",
    english: "27",
    indonesian: "27",
    ngoko: "pitulikur",
    madya: "pitulikur",
    alus: "pitulikur",
  },
  {
    type: "numbers",
    english: "28",
    indonesian: "28",
    ngoko: "wolulikur",
    madya: "wolulikur",
    alus: "wolulikur",
  },
  {
    type: "numbers",
    english: "29",
    indonesian: "29",
    ngoko: "sanga likur",
    madya: "sangalikur",
    alus: "sangalikur",
  },
  {
    type: "numbers",
    english: "30",
    indonesian: "30",
    ngoko: "telung puluh",
    madya: "tigang dasa",
    alus: "tigang dasa",
  },
  {
    type: "numbers",
    english: "31",
    indonesian: "31",
    ngoko: "telung puluh siji",
    madya: "tigang dasa setunggal",
    alus: "tigang dasa setunggal",
  },
  {
    type: "numbers",
    english: "32",
    indonesian: "32",
    ngoko: "telung puluh loro",
    madya: "tigang dasa kalih",
    alus: "tigang dasa kalih",
  },
  {
    type: "numbers",
    english: "33",
    indonesian: "33",
    ngoko: "telung puluh telu",
    madya: "tigang dasa tiga",
    alus: "tigang dasa tiga",
  },
  {
    type: "numbers",
    english: "34",
    indonesian: "34",
    ngoko: "telung puluh papat",
    madya: "tigang dasa sekawan",
    alus: "tigang dasa sekawan",
  },
  {
    type: "numbers",
    english: "35",
    indonesian: "35",
    ngoko: "telung puluh lima",
    madya: "tigang dasa gangsal",
    alus: "tigang dasa gangsal",
  },
  {
    type: "numbers",
    english: "36",
    indonesian: "36",
    ngoko: "telung puluh enem",
    madya: "tigang dasa enem",
    alus: "tigang dasa enem",
  },
  {
    type: "numbers",
    english: "37",
    indonesian: "37",
    ngoko: "telung puluh pitu",
    madya: "tigang dasa pitu",
    alus: "tigang dasa pitu",
  },
  {
    type: "numbers",
    english: "38",
    indonesian: "38",
    ngoko: "telung puluh wolu",
    madya: "tigang dasa wolu",
    alus: "tigang dasa wolu",
  },
  {
    type: "numbers",
    english: "39",
    indonesian: "39",
    ngoko: "telung puluh sanga",
    madya: "tigang dasa sanga",
    alus: "tigang dasa sanga",
  },
  {
    type: "numbers",
    english: "40",
    indonesian: "40",
    ngoko: "patang puluh",
    madya: "sekawan dasa",
    alus: "sekawan dasa",
  },
  {
    type: "numbers",
    english: "41",
    indonesian: "41",
    ngoko: "patang puluh siji",
    madya: "sekawan dasa setunggal",
    alus: "sekawan dasa setunggal",
  },
  {
    type: "numbers",
    english: "42",
    indonesian: "42",
    ngoko: "patang puluh loro",
    madya: "sekawan dasa kalih",
    alus: "sekawan dasa kalih",
  },
  {
    type: "numbers",
    english: "43",
    indonesian: "43",
    ngoko: "patang puluh telu",
    madya: "sekawan dasa tiga",
    alus: "sekawan dasa tiga",
  },
  {
    type: "numbers",
    english: "44",
    indonesian: "44",
    ngoko: "patang puluh papat",
    madya: "sekawan dasa sekawan",
    alus: "sekawan dasa sekawan",
  },
  {
    type: "numbers",
    english: "45",
    indonesian: "45",
    ngoko: "patang puluh lima",
    madya: "sekawan dasa gangsal",
    alus: "sekawan dasa gangsal",
  },
  {
    type: "numbers",
    english: "46",
    indonesian: "46",
    ngoko: "patang puluh enem",
    madya: "sekawan dasa enem",
    alus: "sekawan dasa enem",
  },
  {
    type: "numbers",
    english: "47",
    indonesian: "47",
    ngoko: "patang puluh pitu",
    madya: "sekawan dasa pitu",
    alus: "sekawan dasa pitu",
  },
  {
    type: "numbers",
    english: "48",
    indonesian: "48",
    ngoko: "patang puluh wolu",
    madya: "sekawan dasa wolu",
    alus: "sekawan dasa wolu",
  },
  {
    type: "numbers",
    english: "49",
    indonesian: "49",
    ngoko: "patang puluh sanga",
    madya: "sekawan dasa sanga",
    alus: "sekawan dasa sanga",
  },
  {
    type: "numbers",
    english: "50",
    indonesian: "50",
    ngoko: "seket",
    madya: "seket",
    alus: "seket",
  },
  {
    type: "numbers",
    english: "51",
    indonesian: "51",
    ngoko: "seket siji",
    madya: "seket setunggal",
    alus: "seket setunggal",
  },
  {
    type: "numbers",
    english: "52",
    indonesian: "52",
    ngoko: "seket loro",
    madya: "seket kalih",
    alus: "seket kalih",
  },
  {
    type: "numbers",
    english: "53",
    indonesian: "53",
    ngoko: "seket telu",
    madya: "seket tiga",
    alus: "seket tiga",
  },
  {
    type: "numbers",
    english: "54",
    indonesian: "54",
    ngoko: "seket papat",
    madya: "seket sekawan",
    alus: "seket sekawan",
  },
  {
    type: "numbers",
    english: "55",
    indonesian: "55",
    ngoko: "seket lima",
    madya: "seket gangsal",
    alus: "seket gangsal",
  },
  {
    type: "numbers",
    english: "56",
    indonesian: "56",
    ngoko: "seket enem",
    madya: "seket enem",
    alus: "seket enem",
  },
  {
    type: "numbers",
    english: "57",
    indonesian: "57",
    ngoko: "seket pitu",
    madya: "seket pitu",
    alus: "seket pitu",
  },
  {
    type: "numbers",
    english: "58",
    indonesian: "58",
    ngoko: "seket wolu",
    madya: "seket wolu",
    alus: "seket wolu",
  },
  {
    type: "numbers",
    english: "59",
    indonesian: "59",
    ngoko: "seket sanga",
    madya: "seket sanga",
    alus: "seket sanga",
  },
  {
    type: "numbers",
    english: "60",
    indonesian: "60",
    ngoko: "sewidak",
    madya: "sewidak",
    alus: "sewidak",
  },
  {
    type: "numbers",
    english: "61",
    indonesian: "61",
    ngoko: "sewidak siji",
    madya: "sewidak setunggal",
    alus: "sewidak setunggal",
  },
  {
    type: "numbers",
    english: "62",
    indonesian: "62",
    ngoko: "sewidak loro",
    madya: "sewidak kalih",
    alus: "sewidak kalih",
  },
  {
    type: "numbers",
    english: "63",
    indonesian: "63",
    ngoko: "sewidak telu",
    madya: "sewidak tiga",
    alus: "sewidak tiga",
  },
  {
    type: "numbers",
    english: "64",
    indonesian: "64",
    ngoko: "sewidak papat",
    madya: "sewidak sekawan",
    alus: "sewidak sekawan",
  },
  {
    type: "numbers",
    english: "65",
    indonesian: "65",
    ngoko: "sewidak lima",
    madya: "sewidak gangsal",
    alus: "sewidak gangsal",
  },
  {
    type: "numbers",
    english: "66",
    indonesian: "66",
    ngoko: "sewidak enem",
    madya: "sewidak enem",
    alus: "sewidak enem",
  },
  {
    type: "numbers",
    english: "67",
    indonesian: "67",
    ngoko: "sewidak pitu",
    madya: "sewidak pitu",
    alus: "sewidak pitu",
  },
  {
    type: "numbers",
    english: "68",
    indonesian: "68",
    ngoko: "sewidak wolu",
    madya: "sewidak wolu",
    alus: "sewidak wolu",
  },
  {
    type: "numbers",
    english: "69",
    indonesian: "69",
    ngoko: "sewidak sanga",
    madya: "sewidak sanga",
    alus: "sewidak sanga",
  },
  {
    type: "numbers",
    english: "70",
    indonesian: "70",
    ngoko: "pitung puluh",
    madya: "pitung dasa",
    alus: "pitung dasa",
  },
  {
    type: "numbers",
    english: "71",
    indonesian: "71",
    ngoko: "pitung puluh siji",
    madya: "pitung dasa setunggal",
    alus: "pitung dasa setunggal",
  },
  {
    type: "numbers",
    english: "72",
    indonesian: "72",
    ngoko: "pitung puluh loro",
    madya: "pitung dasa kalih",
    alus: "pitung dasa kalih",
  },
  {
    type: "numbers",
    english: "73",
    indonesian: "73",
    ngoko: "pitung puluh telu",
    madya: "pitung dasa tiga",
    alus: "pitung dasa tiga",
  },
  {
    type: "numbers",
    english: "74",
    indonesian: "74",
    ngoko: "pitung puluh papat",
    madya: "pitung dasa sekawan",
    alus: "pitung dasa sekawan",
  },
  {
    type: "numbers",
    english: "75",
    indonesian: "75",
    ngoko: "pitung puluh lima",
    madya: "pitung dasa gangsal",
    alus: "pitung dasa gangsal",
  },
  {
    type: "numbers",
    english: "76",
    indonesian: "76",
    ngoko: "pitung puluh enem",
    madya: "pitung dasa enem",
    alus: "pitung dasa enem",
  },
  {
    type: "numbers",
    english: "77",
    indonesian: "77",
    ngoko: "pitung puluh pitu",
    madya: "pitung dasa pitu",
    alus: "pitung dasa pitu",
  },
  {
    type: "numbers",
    english: "78",
    indonesian: "78",
    ngoko: "pitung puluh wolu",
    madya: "pitung dasa wolu",
    alus: "pitung dasa wolu",
  },
  {
    type: "numbers",
    english: "79",
    indonesian: "79",
    ngoko: "pitung puluh sanga",
    madya: "pitung dasa sanga",
    alus: "pitung dasa sanga",
  },
  {
    type: "numbers",
    english: "80",
    indonesian: "80",
    ngoko: "wolung puluh",
    madya: "wolung dasa",
    alus: "wolung dasa",
  },
  {
    type: "numbers",
    english: "81",
    indonesian: "81",
    ngoko: "wolung puluh siji",
    madya: "wolung dasa setunggal",
    alus: "wolung dasa setunggal",
  },
  {
    type: "numbers",
    english: "82",
    indonesian: "82",
    ngoko: "wolung puluh loro",
    madya: "wolung dasa kalih",
    alus: "wolung dasa kalih",
  },
  {
    type: "numbers",
    english: "83",
    indonesian: "83",
    ngoko: "wolung puluh telu",
    madya: "wolung dasa tiga",
    alus: "wolung dasa tiga",
  },
  {
    type: "numbers",
    english: "84",
    indonesian: "84",
    ngoko: "wolung puluh papat",
    madya: "wolung dasa sekawan",
    alus: "wolung dasa sekawan",
  },
  {
    type: "numbers",
    english: "85",
    indonesian: "85",
    ngoko: "wolung puluh lima",
    madya: "wolung dasa gangsal",
    alus: "wolung dasa gangsal",
  },
  {
    type: "numbers",
    english: "86",
    indonesian: "86",
    ngoko: "wolung puluh enem",
    madya: "wolung dasa enem",
    alus: "wolung dasa enem",
  },
  {
    type: "numbers",
    english: "87",
    indonesian: "87",
    ngoko: "wolung puluh pitu",
    madya: "wolung dasa pitu",
    alus: "wolung dasa pitu",
  },
  {
    type: "numbers",
    english: "88",
    indonesian: "88",
    ngoko: "wolung puluh wolu",
    madya: "wolung dasa wolu",
    alus: "wolung dasa wolu",
  },
  {
    type: "numbers",
    english: "89",
    indonesian: "89",
    ngoko: "wolung puluh sanga",
    madya: "wolung dasa sanga",
    alus: "wolung dasa sanga",
  },
  {
    type: "numbers",
    english: "90",
    indonesian: "90",
    ngoko: "sangang puluh",
    madya: "sangang dasa",
    alus: "sangang dasa",
  },
  {
    type: "numbers",
    english: "91",
    indonesian: "91",
    ngoko: "sangang puluh siji",
    madya: "sangang dasa setunggal",
    alus: "sangang dasa setunggal",
  },
  {
    type: "numbers",
    english: "92",
    indonesian: "92",
    ngoko: "sangang puluh loro",
    madya: "sangang dasa kalih",
    alus: "sangang dasa kalih",
  },
  {
    type: "numbers",
    english: "93",
    indonesian: "93",
    ngoko: "sangang puluh telu",
    madya: "sangang dasa tiga",
    alus: "sangang dasa tiga",
  },
  {
    type: "numbers",
    english: "94",
    indonesian: "94",
    ngoko: "sangang puluh papat",
    madya: "sangang dasa sekawan",
    alus: "sangang dasa sekawan",
  },
  {
    type: "numbers",
    english: "95",
    indonesian: "95",
    ngoko: "sangang puluh lima",
    madya: "sangang dasa gangsal",
    alus: "sangang dasa gangsal",
  },
  {
    type: "numbers",
    english: "96",
    indonesian: "96",
    ngoko: "sangang puluh enem",
    madya: "sangang dasa enem",
    alus: "sangang dasa enem",
  },
  {
    type: "numbers",
    english: "97",
    indonesian: "97",
    ngoko: "sangang puluh pitu",
    madya: "sangang dasa pitu",
    alus: "sangang dasa pitu",
  },
  {
    type: "numbers",
    english: "98",
    indonesian: "98",
    ngoko: "sangang puluh wolu",
    madya: "sangang dasa wolu",
    alus: "sangang dasa wolu",
  },
  {
    type: "numbers",
    english: "99",
    indonesian: "99",
    ngoko: "sangang puluh sanga",
    madya: "sangang dasa sanga",
    alus: "sangang dasa sanga",
  },
  {
    type: "numbers",
    english: "100",
    indonesian: "100",
    ngoko: "satus",
    madya: "setunggal atus",
    alus: "setunggal atus",
  },
];

export const positions = [
  {
    position: [0, 0, -15],
  },
  {
    position: [3, 0, -15],
  },
  {
    position: [-3, 0, -15],
  },
  {
    position: [0, 0, -10],
  },
  {
    position: [3, 0, -10],
  },
  {
    position: [-3, 0, -10],
  },
  {
    position: [3, 0, -5],
  },
  {
    position: [-3, 0, -5],
  },
  {
    position: [0, 0, 0],
  },
  {
    position: [3, 0, 0],
  },
  {
    position: [-3, 0, 0],
  },
];
