/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei"

export default function World(props) {
  const { nodes, materials } = useGLTF("/models/environment/world.glb")
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 31.697]}>
        <mesh
          geometry={nodes.Plane003.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Plane003_1.geometry}
          material={materials["Banana Trunk"]}
        />
        <mesh
          geometry={nodes.Plane003_2.geometry}
          material={materials["Banana Leaf 3"]}
        />
        <mesh
          geometry={nodes.Plane003_3.geometry}
          material={materials["Banana Leaf 4"]}
        />
        <mesh
          geometry={nodes.Plane003_4.geometry}
          material={materials["Banana Leaf 2"]}
        />
        <mesh
          geometry={nodes.Plane003_5.geometry}
          material={materials["Banana Leaf 1"]}
        />
        <mesh
          geometry={nodes.Plane003_6.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane003_7.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Plane003_8.geometry}
          material={materials["rock.001"]}
        />
        <mesh
          geometry={nodes.Plane003_9.geometry}
          material={materials["rock.002"]}
        />
        <mesh geometry={nodes.Plane003_10.geometry} material={materials.rock} />
        <mesh
          receiveShadow
          geometry={nodes.Plane003_11.geometry}
          material={materials["wood.001"]}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/models/environment/world.glb")
